apps/main/urls.py
from django.urls import path
from apps.main import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

app_name = 'main'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', views.CustomLoginView.as_view(), name='custom_login'),
    path('logout/', views.logout_view, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tameenak-config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
    include
)

urlpatterns = [
    path('tameenak-super-admin', admin.site.urls),
    path('', include('apps.main.urls')),
    path('tameenak-user/', include('apps.tameenak_user.urls.tameenak_user_urls', namespace='tameenak_user')),
    path('tameenak-admin/', include('apps.tameenak_user.urls.tameenak_admin_urls', namespace='tameenak_admin')),
    path('insurance-co/', include('apps.insurance_company.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>
        {% block title %} Tameenak {% endblock %}
    </title>

    <!-- Favicon - loaded as static -->
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/argon.css' v=1.2.0 %}" type="text/css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">

{% include "includes/sidenav.html" %}

<div class="main-content" id="panel">

    {% include "includes/navigation.html" %}

    {% block content %}{% endblock content %}

</div>

{% include "includes/scripts.html" %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

<script src="/assets/js/argon.js?v=1.2.0"></script>

</body>

</html>

templates/layouts/home_page_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        Tameenak {% block title %} All your insurances on one platform {% endblock %}
    </title>

    <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          type="text/css">
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/argon.css' v=1.2.0 %}" type="text/css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="bg-default">

<div class="main-content">

    {% include "includes/home_page_navigation.html" %}

    <!-- Header -->
    <div class="header bg-gradient-info py-7 py-lg-8">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                    <div class="col-lg-5 col-md-6">
                        <h1 class="text-white">
                            <h1 class="text-white">Tameenak</h1>
                        </h1>
                        <p class="text-lead text-light">
                            All your insurances
                            on one platform.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                 xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
        </div>
    </div>

    {% block content %}{% endblock content %}

    {% include "includes/home_page_footer.html" %}

</div>

{% include "includes/scripts.html" %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

<script src="/static/assets/js/argon.js?v=1.2.0"></script>

</body>

</html>

templates/layouts/page-401.html
{% extends 'layouts/home_page_base.html' %}

{% block title %} Error 401 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 401      
              </div>

              <div class="text-center mb-4">
                Unauthorized - <a href="{% url 'main:custom_login' %}" class="btn-outline-info">Login</a>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/layouts/page-403.html
{% extends 'layouts/base.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Please authenticate <a href="{% url 'login' %}">Login</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/static" class="text-light"><small>Home</small></a>
            </div>          
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/layouts/page-404.html
{% extends 'layouts/home_page_base.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="{% url 'main:home' %}" class="btn-outline-info">Home</a>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/layouts/page-500.html
{% extends 'layouts/base.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 500      
              </div>

              <div class="text-center mb-4">
                Server error, please contact support - <a href="{% url 'home' %}">Home</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="{% url 'home' %}" class="text-light"><small>Home</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}