apps/main/urls.py
from django.urls import path
from apps.main import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

app_name = 'main'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', views.CustomLoginView.as_view(), name='custom_login'),
    path('logout/', views.logout_view, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tameenak-config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
    include
)

urlpatterns = [
    path('tameenak-super-admin', admin.site.urls),
    path('', include('apps.main.urls')),
    path('tameenak-user/', include('apps.tameenak_user.urls.tameenak_user_urls', namespace='tameenak_user')),
    path('tameenak-admin/', include('apps.tameenak_user.urls.tameenak_admin_urls', namespace='tameenak_admin')),
    path('insurance-co/', include('apps.insurance_company.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<!-- Footer -->
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
                <a href="https://appseed.us/admin-dashboards/django"
                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
                <a href="https://bit.ly/3fKQZaL"
                   class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a>
                - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
        </div>
    </div>
</footer>

templates/includes/home_page_footer.html
{% load static %}
<footer class="py-5">
    <div class="container">
        <div class="row align-items-center justify-content-xl-between">
            <div class="col-xl-6">
                <div class="copyright text-center text-xl-left text-muted">
                    &copy; 2024
                    <a href="/" class="font-weight-bold ml-1 text-info" target="_blank">
                        Tameenak
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/home_page_navigation.html
{% load static %}
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#">
        <h1 class="text-light font-weight-bold pt-3">Tameenak</h1>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="{% static 'assets/img/brand/blue.png' %}" alt="/">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'main:custom_login' %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'tameenak_user:register' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
    </div>
  </div>
</nav>

templates/includes/navigation.html
{% load static %}
<nav class="navbar navbar-top navbar-expand navbar-dark bg-gradient-info border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                         data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                {% if request.user.tameenakcustomer.picture %}
                                    <img alt="Image placeholder" src="{{ request.user.tameenakcustomer.picture.url }}">
                                {% else %}
                                    <img alt="Image placeholder"
                                         src="{% static 'image/tameenak_user/default_pic.png' %}">
                                {% endif %}
                            </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">
                                    <h6 class="text-light m-0">Welcome!</h6> {{ request.user.username }}
                                </span>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/scripts.html
{% load static %}
<script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>

templates/includes/sidenav.html
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="/">
                <h1 class="text-info font-weight-bold pt-3">Tameenak</h1>
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    {% if "Tameenak Admin" in request.user.groups.all|join:" " %}
                        <li class="nav-item">
                            <a class="nav-link {% if 'dashboard' in request.path %} active {% endif %}"
                               href="{% url "tameenak_admin:admin_dashboard" %}">
                                <i class="ni ni-tv-2 text-primary"></i>
                                <span class="nav-link-text">Dashboard</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if 'dashboard' in request.path %} active {% endif %}"
                               href="{% url "tameenak_user:user_dashboard" %}">
                                <i class="ni ni-tv-2 text-primary"></i>
                                <span class="nav-link-text">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'medical-profile' in request.path %} active {% endif %}"
                               href="{% url "tameenak_user:medical_profile" %}">
                                <i class="fa fa-id-card text-info"></i>
                                <span class="nav-link-text">Medical Profile</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'user-history' in request.path %} active {% endif %}"
                               href="{% url 'tameenak_user:user_history' %}">
                                <i class="fa fa-history text-primary"></i>
                                <span class="nav-link-text">Your History</span>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:logout' %}">
                            <i class="ni ni-user-run text-red"></i>
                            <span class="nav-link-text">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>